//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOBoxerList
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boxer
    {
        public string BoxerId { get; set; }
        public string FirstName { get; set; }
        public string NickName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string WeightClass { get; set; }
        public string KOCount { get; set; }
        public string Record { get; set; }
        public string HomeTown { get; set; }
        public string HomeState { get; set; }
    }
}
